# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T10:14:50+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class ARNString(RootModel[constr(min_length=20, max_length=2048)]):
    root: constr(min_length=20, max_length=2048)


class AccessKeyString(RootModel[str]):
    root: str


class AccountId(RootModel[constr(pattern=r'\d+', min_length=1, max_length=15)]):
    root: constr(pattern=r'\d+', min_length=1, max_length=15)


class AmbiguousRoleResolutionType(Enum):
    AuthenticatedRole = 'AuthenticatedRole'
    Deny = 'Deny'


class ClaimName(
    RootModel[
        constr(pattern=r'[\p{L}\p{M}\p{S}\p{N}\p{P}]+', min_length=1, max_length=64)
    ]
):
    root: constr(pattern=r'[\p{L}\p{M}\p{S}\p{N}\p{P}]+', min_length=1, max_length=64)


class ClaimValue(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class ClassicFlow(RootModel[bool]):
    root: bool


class CognitoIdentityProviderClientId(
    RootModel[constr(pattern=r'[\w_]+', min_length=1, max_length=128)]
):
    root: constr(pattern=r'[\w_]+', min_length=1, max_length=128)


class CognitoIdentityProviderName(
    RootModel[constr(pattern=r'[\w._:/-]+', min_length=1, max_length=128)]
):
    root: constr(pattern=r'[\w._:/-]+', min_length=1, max_length=128)


class CognitoIdentityProviderTokenCheck(RootModel[bool]):
    root: bool


class ConcurrentModificationException(RootModel[Any]):
    root: Any


class DateType(RootModel[datetime]):
    root: datetime


class DeveloperProviderName(
    RootModel[constr(pattern=r'[\w._-]+', min_length=1, max_length=128)]
):
    root: constr(pattern=r'[\w._-]+', min_length=1, max_length=128)


class DeveloperUserAlreadyRegisteredException(RootModel[Any]):
    root: Any


class DeveloperUserIdentifier(RootModel[constr(min_length=1, max_length=1024)]):
    root: constr(min_length=1, max_length=1024)


class DeveloperUserIdentifierList(RootModel[List[DeveloperUserIdentifier]]):
    root: List[DeveloperUserIdentifier]


class ErrorCode(Enum):
    AccessDenied = 'AccessDenied'
    InternalServerError = 'InternalServerError'


class ExternalServiceException(RootModel[Any]):
    root: Any


class HideDisabled(RootModel[bool]):
    root: bool


class IdentityId(
    RootModel[constr(pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55)]
):
    root: constr(pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55)


class IdentityIdList(RootModel[List[IdentityId]]):
    root: List[IdentityId] = Field(..., max_length=60, min_length=1)


class IdentityPoolId(
    RootModel[constr(pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55)]
):
    root: constr(pattern=r'[\w-]+:[0-9a-f-]+', min_length=1, max_length=55)


class IdentityPoolName(
    RootModel[constr(pattern=r'[\w\s+=,.@-]+', min_length=1, max_length=128)]
):
    root: constr(pattern=r'[\w\s+=,.@-]+', min_length=1, max_length=128)


class IdentityPoolShortDescription(BaseModel):
    IdentityPoolId_1: Optional[IdentityPoolId] = Field(None, alias='IdentityPoolId')
    IdentityPoolName_1: Optional[IdentityPoolName] = Field(
        None, alias='IdentityPoolName'
    )


class IdentityPoolUnauthenticated(RootModel[bool]):
    root: bool


class IdentityPoolsList(RootModel[List[IdentityPoolShortDescription]]):
    root: List[IdentityPoolShortDescription]


class IdentityProviderId(
    RootModel[constr(pattern=r'[\w.;_/-]+', min_length=1, max_length=128)]
):
    root: constr(pattern=r'[\w.;_/-]+', min_length=1, max_length=128)


class IdentityProviderName(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class IdentityProviderToken(RootModel[constr(min_length=1, max_length=50000)]):
    root: constr(min_length=1, max_length=50000)


class IdentityProviders(RootModel[Optional[Dict[str, IdentityProviderId]]]):
    root: Optional[Dict[str, IdentityProviderId]] = None


class InternalErrorException(RootModel[Any]):
    root: Any


class InvalidIdentityPoolConfigurationException(RootModel[Any]):
    root: Any


class InvalidParameterException(RootModel[Any]):
    root: Any


class LimitExceededException(RootModel[Any]):
    root: Any


class ListTagsForResourceInput(BaseModel):
    ResourceArn: ARNString


class LoginsList(RootModel[List[IdentityProviderName]]):
    root: List[IdentityProviderName]


class LoginsMap(RootModel[Optional[Dict[str, IdentityProviderToken]]]):
    root: Optional[Dict[str, IdentityProviderToken]] = None


class MappingRuleMatchType(Enum):
    Equals = 'Equals'
    Contains = 'Contains'
    StartsWith = 'StartsWith'
    NotEqual = 'NotEqual'


class MergeDeveloperIdentitiesInput(BaseModel):
    DestinationUserIdentifier: DeveloperUserIdentifier
    DeveloperProviderName_1: DeveloperProviderName = Field(
        ..., alias='DeveloperProviderName'
    )
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')
    SourceUserIdentifier: DeveloperUserIdentifier


class MergeDeveloperIdentitiesResponse(BaseModel):
    IdentityId_1: Optional[IdentityId] = Field(None, alias='IdentityId')


class NotAuthorizedException(RootModel[Any]):
    root: Any


class OIDCProviderList(RootModel[List[ARNString]]):
    root: List[ARNString]


class OIDCToken(RootModel[str]):
    root: str


class PaginationKey(
    RootModel[constr(pattern=r'[\S]+', min_length=1, max_length=65535)]
):
    root: constr(pattern=r'[\S]+', min_length=1, max_length=65535)


class PrincipalTagID(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class PrincipalTagValue(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class PrincipalTags(RootModel[Optional[Dict[str, PrincipalTagValue]]]):
    root: Optional[Dict[str, PrincipalTagValue]] = None


class QueryLimit(RootModel[conint(ge=1, le=60)]):
    root: conint(ge=1, le=60)


class ResourceConflictException(RootModel[Any]):
    root: Any


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class RoleMappingType(Enum):
    Token = 'Token'
    Rules = 'Rules'


class RoleType(
    RootModel[constr(pattern=r'(un)?authenticated', min_length=1, max_length=128)]
):
    root: constr(pattern=r'(un)?authenticated', min_length=1, max_length=128)


class RolesMap(RootModel[Optional[Dict[str, ARNString]]]):
    root: Optional[Dict[str, ARNString]] = None


class SAMLProviderList(RootModel[List[ARNString]]):
    root: List[ARNString]


class SecretKeyString(RootModel[str]):
    root: str


class SessionTokenString(RootModel[str]):
    root: str


class TagKeysType(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class TagResourceResponse(BaseModel):
    pass


class TagValueType(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class TokenDuration(RootModel[conint(ge=1, le=86400)]):
    root: conint(ge=1, le=86400)


class TooManyRequestsException(RootModel[Any]):
    root: Any


class UnlinkDeveloperIdentityInput(BaseModel):
    DeveloperProviderName_1: DeveloperProviderName = Field(
        ..., alias='DeveloperProviderName'
    )
    DeveloperUserIdentifier_1: DeveloperUserIdentifier = Field(
        ..., alias='DeveloperUserIdentifier'
    )
    IdentityId_1: IdentityId = Field(..., alias='IdentityId')
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')


class UnlinkIdentityInput(BaseModel):
    IdentityId_1: IdentityId = Field(..., alias='IdentityId')
    Logins: LoginsMap
    LoginsToRemove: LoginsList


class UnprocessedIdentityId(BaseModel):
    ErrorCode_1: Optional[ErrorCode] = Field(None, alias='ErrorCode')
    IdentityId_1: Optional[IdentityId] = Field(None, alias='IdentityId')


class UnprocessedIdentityIdList(RootModel[List[UnprocessedIdentityId]]):
    root: List[UnprocessedIdentityId] = Field(..., max_length=60)


class UntagResourceResponse(BaseModel):
    pass


class UseDefaults(RootModel[bool]):
    root: bool


class XAmzTarget(Enum):
    AWSCognitoIdentityService_CreateIdentityPool = (
        'AWSCognitoIdentityService.CreateIdentityPool'
    )


class XAmzTarget1(Enum):
    AWSCognitoIdentityService_DeleteIdentities = (
        'AWSCognitoIdentityService.DeleteIdentities'
    )


class XAmzTarget2(Enum):
    AWSCognitoIdentityService_DeleteIdentityPool = (
        'AWSCognitoIdentityService.DeleteIdentityPool'
    )


class XAmzTarget3(Enum):
    AWSCognitoIdentityService_DescribeIdentity = (
        'AWSCognitoIdentityService.DescribeIdentity'
    )


class XAmzTarget4(Enum):
    AWSCognitoIdentityService_DescribeIdentityPool = (
        'AWSCognitoIdentityService.DescribeIdentityPool'
    )


class XAmzTarget5(Enum):
    AWSCognitoIdentityService_GetCredentialsForIdentity = (
        'AWSCognitoIdentityService.GetCredentialsForIdentity'
    )


class XAmzTarget6(Enum):
    AWSCognitoIdentityService_GetId = 'AWSCognitoIdentityService.GetId'


class XAmzTarget7(Enum):
    AWSCognitoIdentityService_GetIdentityPoolRoles = (
        'AWSCognitoIdentityService.GetIdentityPoolRoles'
    )


class XAmzTarget8(Enum):
    AWSCognitoIdentityService_GetOpenIdToken = (
        'AWSCognitoIdentityService.GetOpenIdToken'
    )


class XAmzTarget9(Enum):
    AWSCognitoIdentityService_GetOpenIdTokenForDeveloperIdentity = (
        'AWSCognitoIdentityService.GetOpenIdTokenForDeveloperIdentity'
    )


class XAmzTarget10(Enum):
    AWSCognitoIdentityService_GetPrincipalTagAttributeMap = (
        'AWSCognitoIdentityService.GetPrincipalTagAttributeMap'
    )


class XAmzTarget11(Enum):
    AWSCognitoIdentityService_ListIdentities = (
        'AWSCognitoIdentityService.ListIdentities'
    )


class XAmzTarget12(Enum):
    AWSCognitoIdentityService_ListIdentityPools = (
        'AWSCognitoIdentityService.ListIdentityPools'
    )


class XAmzTarget13(Enum):
    AWSCognitoIdentityService_ListTagsForResource = (
        'AWSCognitoIdentityService.ListTagsForResource'
    )


class XAmzTarget14(Enum):
    AWSCognitoIdentityService_LookupDeveloperIdentity = (
        'AWSCognitoIdentityService.LookupDeveloperIdentity'
    )


class XAmzTarget15(Enum):
    AWSCognitoIdentityService_MergeDeveloperIdentities = (
        'AWSCognitoIdentityService.MergeDeveloperIdentities'
    )


class XAmzTarget16(Enum):
    AWSCognitoIdentityService_SetIdentityPoolRoles = (
        'AWSCognitoIdentityService.SetIdentityPoolRoles'
    )


class XAmzTarget17(Enum):
    AWSCognitoIdentityService_SetPrincipalTagAttributeMap = (
        'AWSCognitoIdentityService.SetPrincipalTagAttributeMap'
    )


class XAmzTarget18(Enum):
    AWSCognitoIdentityService_TagResource = 'AWSCognitoIdentityService.TagResource'


class XAmzTarget19(Enum):
    AWSCognitoIdentityService_UnlinkDeveloperIdentity = (
        'AWSCognitoIdentityService.UnlinkDeveloperIdentity'
    )


class XAmzTarget20(Enum):
    AWSCognitoIdentityService_UnlinkIdentity = (
        'AWSCognitoIdentityService.UnlinkIdentity'
    )


class XAmzTarget21(Enum):
    AWSCognitoIdentityService_UntagResource = 'AWSCognitoIdentityService.UntagResource'


class XAmzTarget22(Enum):
    AWSCognitoIdentityService_UpdateIdentityPool = (
        'AWSCognitoIdentityService.UpdateIdentityPool'
    )


class CognitoIdentityProvider(BaseModel):
    ClientId: Optional[CognitoIdentityProviderClientId] = None
    ProviderName: Optional[CognitoIdentityProviderName] = None
    ServerSideTokenCheck: Optional[CognitoIdentityProviderTokenCheck] = None


class CognitoIdentityProviderList(RootModel[List[CognitoIdentityProvider]]):
    root: List[CognitoIdentityProvider]


class Credentials(BaseModel):
    AccessKeyId: Optional[AccessKeyString] = None
    Expiration: Optional[DateType] = None
    SecretKey: Optional[SecretKeyString] = None
    SessionToken: Optional[SessionTokenString] = None


class DeleteIdentitiesInput(BaseModel):
    IdentityIdsToDelete: IdentityIdList


class DeleteIdentitiesResponse(BaseModel):
    UnprocessedIdentityIds: Optional[UnprocessedIdentityIdList] = None


class DeleteIdentityPoolInput(BaseModel):
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')


class DescribeIdentityInput(BaseModel):
    IdentityId_1: IdentityId = Field(..., alias='IdentityId')


class DescribeIdentityPoolInput(BaseModel):
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')


class GetCredentialsForIdentityInput(BaseModel):
    CustomRoleArn: Optional[ARNString] = None
    IdentityId_1: IdentityId = Field(..., alias='IdentityId')
    Logins: Optional[LoginsMap] = None


class GetCredentialsForIdentityResponse(BaseModel):
    Credentials_1: Optional[Credentials] = Field(None, alias='Credentials')
    IdentityId_1: Optional[IdentityId] = Field(None, alias='IdentityId')


class GetIdInput(BaseModel):
    AccountId_1: Optional[AccountId] = Field(None, alias='AccountId')
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')
    Logins: Optional[LoginsMap] = None


class GetIdResponse(BaseModel):
    IdentityId_1: Optional[IdentityId] = Field(None, alias='IdentityId')


class GetIdentityPoolRolesInput(BaseModel):
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')


class GetOpenIdTokenForDeveloperIdentityInput(BaseModel):
    IdentityId_1: Optional[IdentityId] = Field(None, alias='IdentityId')
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')
    Logins: LoginsMap
    PrincipalTags_1: Optional[PrincipalTags] = Field(None, alias='PrincipalTags')
    TokenDuration_1: Optional[TokenDuration] = Field(None, alias='TokenDuration')


class GetOpenIdTokenForDeveloperIdentityResponse(BaseModel):
    IdentityId_1: Optional[IdentityId] = Field(None, alias='IdentityId')
    Token: Optional[OIDCToken] = None


class GetOpenIdTokenInput(BaseModel):
    IdentityId_1: IdentityId = Field(..., alias='IdentityId')
    Logins: Optional[LoginsMap] = None


class GetOpenIdTokenResponse(BaseModel):
    IdentityId_1: Optional[IdentityId] = Field(None, alias='IdentityId')
    Token: Optional[OIDCToken] = None


class GetPrincipalTagAttributeMapInput(BaseModel):
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')
    IdentityProviderName_1: IdentityProviderName = Field(
        ..., alias='IdentityProviderName'
    )


class GetPrincipalTagAttributeMapResponse(BaseModel):
    IdentityPoolId_1: Optional[IdentityPoolId] = Field(None, alias='IdentityPoolId')
    IdentityProviderName_1: Optional[IdentityProviderName] = Field(
        None, alias='IdentityProviderName'
    )
    PrincipalTags_1: Optional[PrincipalTags] = Field(None, alias='PrincipalTags')
    UseDefaults_1: Optional[UseDefaults] = Field(None, alias='UseDefaults')


class IdentityDescription(BaseModel):
    CreationDate: Optional[DateType] = None
    IdentityId_1: Optional[IdentityId] = Field(None, alias='IdentityId')
    LastModifiedDate: Optional[DateType] = None
    Logins: Optional[LoginsList] = None


class IdentityPoolTagsListType(RootModel[List[TagKeysType]]):
    root: List[TagKeysType]


class IdentityPoolTagsType(RootModel[Optional[Dict[str, TagValueType]]]):
    root: Optional[Dict[str, TagValueType]] = None


class ListIdentitiesInput(BaseModel):
    HideDisabled_1: Optional[HideDisabled] = Field(None, alias='HideDisabled')
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')
    MaxResults: QueryLimit
    NextToken: Optional[PaginationKey] = None


class ListIdentityPoolsInput(BaseModel):
    MaxResults: QueryLimit
    NextToken: Optional[PaginationKey] = None


class ListIdentityPoolsResponse(BaseModel):
    IdentityPools: Optional[IdentityPoolsList] = None
    NextToken: Optional[PaginationKey] = None


class ListTagsForResourceResponse(BaseModel):
    Tags: Optional[IdentityPoolTagsType] = None


class LookupDeveloperIdentityInput(BaseModel):
    DeveloperUserIdentifier_1: Optional[DeveloperUserIdentifier] = Field(
        None, alias='DeveloperUserIdentifier'
    )
    IdentityId_1: Optional[IdentityId] = Field(None, alias='IdentityId')
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')
    MaxResults: Optional[QueryLimit] = None
    NextToken: Optional[PaginationKey] = None


class LookupDeveloperIdentityResponse(BaseModel):
    DeveloperUserIdentifierList_1: Optional[DeveloperUserIdentifierList] = Field(
        None, alias='DeveloperUserIdentifierList'
    )
    IdentityId_1: Optional[IdentityId] = Field(None, alias='IdentityId')
    NextToken: Optional[PaginationKey] = None


class MappingRule(BaseModel):
    Claim: ClaimName
    MatchType: MappingRuleMatchType
    RoleARN: ARNString
    Value: ClaimValue


class MappingRulesList(RootModel[List[MappingRule]]):
    root: List[MappingRule] = Field(..., max_length=400, min_length=1)


class RulesConfigurationType(BaseModel):
    Rules: MappingRulesList


class SetPrincipalTagAttributeMapInput(BaseModel):
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')
    IdentityProviderName_1: IdentityProviderName = Field(
        ..., alias='IdentityProviderName'
    )
    PrincipalTags_1: Optional[PrincipalTags] = Field(None, alias='PrincipalTags')
    UseDefaults_1: Optional[UseDefaults] = Field(None, alias='UseDefaults')


class SetPrincipalTagAttributeMapResponse(BaseModel):
    IdentityPoolId_1: Optional[IdentityPoolId] = Field(None, alias='IdentityPoolId')
    IdentityProviderName_1: Optional[IdentityProviderName] = Field(
        None, alias='IdentityProviderName'
    )
    PrincipalTags_1: Optional[PrincipalTags] = Field(None, alias='PrincipalTags')
    UseDefaults_1: Optional[UseDefaults] = Field(None, alias='UseDefaults')


class TagResourceInput(BaseModel):
    ResourceArn: ARNString
    Tags: IdentityPoolTagsType


class UntagResourceInput(BaseModel):
    ResourceArn: ARNString
    TagKeys: IdentityPoolTagsListType


class CreateIdentityPoolInput(BaseModel):
    AllowClassicFlow: Optional[ClassicFlow] = None
    AllowUnauthenticatedIdentities: IdentityPoolUnauthenticated
    CognitoIdentityProviders: Optional[CognitoIdentityProviderList] = None
    DeveloperProviderName_1: Optional[DeveloperProviderName] = Field(
        None, alias='DeveloperProviderName'
    )
    IdentityPoolName_1: IdentityPoolName = Field(..., alias='IdentityPoolName')
    IdentityPoolTags: Optional[IdentityPoolTagsType] = None
    OpenIdConnectProviderARNs: Optional[OIDCProviderList] = None
    SamlProviderARNs: Optional[SAMLProviderList] = None
    SupportedLoginProviders: Optional[IdentityProviders] = None


class IdentitiesList(RootModel[List[IdentityDescription]]):
    root: List[IdentityDescription]


class IdentityPool(BaseModel):
    AllowClassicFlow: Optional[ClassicFlow] = None
    AllowUnauthenticatedIdentities: IdentityPoolUnauthenticated
    CognitoIdentityProviders: Optional[CognitoIdentityProviderList] = None
    DeveloperProviderName_1: Optional[DeveloperProviderName] = Field(
        None, alias='DeveloperProviderName'
    )
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')
    IdentityPoolName_1: IdentityPoolName = Field(..., alias='IdentityPoolName')
    IdentityPoolTags: Optional[IdentityPoolTagsType] = None
    OpenIdConnectProviderARNs: Optional[OIDCProviderList] = None
    SamlProviderARNs: Optional[SAMLProviderList] = None
    SupportedLoginProviders: Optional[IdentityProviders] = None


class ListIdentitiesResponse(BaseModel):
    Identities: Optional[IdentitiesList] = None
    IdentityPoolId_1: Optional[IdentityPoolId] = Field(None, alias='IdentityPoolId')
    NextToken: Optional[PaginationKey] = None


class RoleMapping(BaseModel):
    AmbiguousRoleResolution: Optional[AmbiguousRoleResolutionType] = None
    RulesConfiguration: Optional[RulesConfigurationType] = None
    Type: RoleMappingType


class RoleMappingMap(RootModel[Optional[Dict[str, RoleMapping]]]):
    root: Optional[Dict[str, RoleMapping]] = None


class SetIdentityPoolRolesInput(BaseModel):
    IdentityPoolId_1: IdentityPoolId = Field(..., alias='IdentityPoolId')
    RoleMappings: Optional[RoleMappingMap] = None
    Roles: RolesMap


class GetIdentityPoolRolesResponse(BaseModel):
    IdentityPoolId_1: Optional[IdentityPoolId] = Field(None, alias='IdentityPoolId')
    RoleMappings: Optional[RoleMappingMap] = None
    Roles: Optional[RolesMap] = None
